CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experience_level VARCHAR(255) NOT NULL,
  score INTEGER NOT NULL,
  score_summary TEXT,
  matched_skills TEXT,
  missing_keywords TEXT,
  top_fixes TEXT,
  bullet_suggestions TEXT,
  interview_questions TEXT,
  prep_plan TEXT,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  experience_level VARCHAR(255),
  country VARCHAR(255),
  report_id BIGINT,
  consent BOOLEAN NOT NULL,
  source VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT,
  email VARCHAR(255),
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_leads_report_id ON leads (report_id);
CREATE INDEX idx_feedback_report_id ON feedback (report_id);
