CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name VARCHAR(80) NOT NULL,
  page_path VARCHAR(255),
  report_public_id UUID,
  experience_level VARCHAR(255),
  country VARCHAR(255),
  source VARCHAR(255),
  utm_source VARCHAR(255),
  utm_medium VARCHAR(255),
  utm_campaign VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  metadata_json TEXT
);

CREATE INDEX idx_events_event_name ON events (event_name);
CREATE INDEX idx_events_report_public_id ON events (report_public_id);
CREATE INDEX idx_events_created_at ON events (created_at);
