ALTER TABLE reports ADD COLUMN IF NOT EXISTS score_breakdown TEXT;

CREATE TABLE outcomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT,
  outcome_type VARCHAR(40) NOT NULL,
  usefulness_rating INTEGER,
  got_recruiter_reply BOOLEAN,
  got_interview BOOLEAN,
  applied_with_this_resume BOOLEAN,
  message TEXT,
  email VARCHAR(255),
  created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_outcomes_report_id ON outcomes (report_id);
CREATE INDEX idx_outcomes_outcome_type ON outcomes (outcome_type);
CREATE INDEX idx_outcomes_created_at ON outcomes (created_at);
