-- Audit trail for every payment link we create and every payment Razorpay confirms.
-- Needed to answer "I paid and did not get my report" without guessing, and to look up a
-- report's existing link instead of creating a duplicate (Razorpay requires reference_id to be
-- unique per link). Deliberately holds no personal data: ids, amount, status, timestamps only.
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_public_id UUID NOT NULL,
  provider VARCHAR(20) NOT NULL,
  payment_link_id VARCHAR(80),
  payment_link_url VARCHAR(500),
  provider_payment_id VARCHAR(80),
  amount_paise INTEGER NOT NULL,
  currency VARCHAR(8) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  paid_at TIMESTAMP
);

CREATE INDEX idx_payments_report_public_id ON payments (report_public_id);
CREATE UNIQUE INDEX idx_payments_payment_link_id ON payments (payment_link_id);
CREATE INDEX idx_payments_status ON payments (status);
